from __future__ import annotations

import zipfile
from pathlib import Path

import pytest

from bilin_api.article_store import (
    bundle_path_for_arxiv,
    create_note_patch,
    create_translation_variant,
    make_asset,
    make_block,
    read_manifest,
    replace_document,
    upsert_arxiv_revision,
)
from bilin_api.export_service import export_article, html_table_to_markdown, queue_article_export
from bilin_api.note_service import accept_article_note_patch
from bilin_api.repositories import create_library, get_job
from bilin_api.schemas import (
    ArticleExportKind,
    ArticleExportRequest,
    ArticleManifest,
    DocumentBlock,
    JobStatus,
    JobType,
    Library,
    LibraryCreate,
)
from bilin_api.worker import run_worker


@pytest.mark.asyncio
async def test_export_source_translation_bilingual_and_notes(
    bilin_home: Path,
    tmp_path: Path,
) -> None:
    library, revision_id, blocks = await prepare_export_fixture(tmp_path)
    await create_translation_variant(
        library=library,
        block=blocks[1],
        target_language="zh-CN",
        raw_markdown="已翻译段落。",
        provider_profile_id="provider",
        model="model",
        glossary_version="glossary:none",
    )
    patch = await create_note_patch(
        library,
        revision_id,
        title="精读模板",
        patch_markdown="## Background\n\nAccepted note [p-0001].",
        source_refs=["p-0001"],
    )
    await accept_article_note_patch(library, patch.id)

    source = await export_article(
        library,
        revision_id,
        ArticleExportRequest(kind=ArticleExportKind.source_markdown),
    )
    source_markdown, source_names = read_markdown_export(source.path)
    assert source.file_name == "export-fixture-source.zip"
    assert source.metadata["relative_path"] == "export/export-fixture-source.zip"
    assert source.metadata["content_notice"] == "bilin-content-notice:v1"
    assert "Generated by Ilios for local study" in source_markdown
    assert '<a id="p-0001"></a>' not in source_markdown
    assert "Article revision:" not in source_markdown
    assert "A paragraph to translate." in source_markdown
    assert "export-fixture-source.assets/fig-0001.png" in source_markdown
    assert "export-fixture-source.assets/fig-0001.png" in source_names

    translated = await export_article(
        library,
        revision_id,
        ArticleExportRequest(kind=ArticleExportKind.translated_markdown, target_language="zh-CN"),
    )
    translated_markdown, _ = read_markdown_export(translated.path)
    assert translated.file_name == "export-fixture-translation-zh-CN.zip"
    assert "已翻译段落。" in translated_markdown
    assert "E=mc^2" in translated_markdown
    assert "<!-- untranslated:fig-0001 -->" not in translated_markdown
    assert translated.missing_translation_block_uids == ["fig-0001"]

    bilingual = await export_article(
        library,
        revision_id,
        ArticleExportRequest(kind=ArticleExportKind.bilingual_markdown, target_language="zh-CN"),
    )
    bilingual_markdown, _ = read_markdown_export(bilingual.path)
    assert "**Source**" in bilingual_markdown
    assert "**Translation (zh-CN)**" in bilingual_markdown
    assert "p-0001" not in bilingual_markdown

    notes = await export_article(
        library,
        revision_id,
        ArticleExportRequest(kind=ArticleExportKind.lecture_notes),
    )
    notes_markdown, _ = read_markdown_export(notes.path)
    assert notes.file_name == "export-fixture-lecture-notes.zip"
    assert "Accepted note" in notes_markdown
    assert "Article revision:" not in notes_markdown
    assert "bilin-note-patch" not in notes_markdown
    manifest = read_manifest(Path(notes.metadata["bundle_path"]))
    assert manifest is not None
    assert (
        manifest.generated_artifacts["exports"]["lecture_notes"]["metadata"]["relative_path"]
        == "export/export-fixture-lecture-notes.zip"
    )


@pytest.mark.asyncio
async def test_export_bundle_zip_contains_bundle_artifacts(
    bilin_home: Path,
    tmp_path: Path,
) -> None:
    library, revision_id, _ = await prepare_export_fixture(tmp_path)
    result = await export_article(
        library,
        revision_id,
        ArticleExportRequest(kind=ArticleExportKind.bundle_zip),
    )
    assert result.file_name == "article-bundle.zip"
    with zipfile.ZipFile(result.path) as archive:
        names = set(archive.namelist())
        notice = archive.read("BILIN_CONTENT_NOTICE.txt").decode("utf-8")
    assert "BILIN_CONTENT_NOTICE.txt" in names
    assert "Generated by Ilios for local research and study use" in notice
    assert "manifest.json" in names
    assert "document/source.md" in names
    assert "export/article-bundle.zip" not in names


@pytest.mark.asyncio
async def test_markdown_export_deduplicates_title_and_stabilizes_display_math(
    bilin_home: Path,
    tmp_path: Path,
) -> None:
    library = await create_library(
        LibraryCreate(name="Math Export", path=str(tmp_path / "library")),
    )
    bundle_path = bundle_path_for_arxiv(library, "2401.00006", "v1")
    _, revision = await upsert_arxiv_revision(
        library,
        bare_id="2401.00006",
        version="v1",
        title="A Stable Markdown Export",
        bundle_path=bundle_path,
        metadata={},
    )
    blocks = [
        make_block(
            revision.id,
            block_uid="sec-title",
            structural_path="00001",
            block_type="section",
            source_markdown="A Stable Markdown Export",
            metadata={"level": 1},
        ),
        make_block(
            revision.id,
            block_uid="p-math",
            structural_path="00002",
            block_type="paragraph",
            source_markdown=r"Inline math $\bm{x}=\argmax_y f(y)$ should render.",
        ),
        make_block(
            revision.id,
            block_uid="eq-display",
            structural_path="00003",
            block_type="equation",
            source_markdown=r"\begin{align} \bm{x} & = \argmax_y f(y) \label{eq:x} \end{align}",
        ),
    ]
    await replace_document(
        library,
        revision,
        ArticleManifest(article_revision_id=revision.id, source="arxiv"),
        blocks,
        [],
        "\n\n".join(block.source_markdown for block in blocks),
    )

    result = await export_article(
        library,
        revision.id,
        ArticleExportRequest(kind=ArticleExportKind.source_markdown),
    )
    markdown, _ = read_markdown_export(result.path)

    assert markdown.count("# A Stable Markdown Export") == 1
    assert r"$\boldsymbol{x}=\operatorname*{arg\,max}_y f(y)$" in markdown
    assert "$$\n\\begin{aligned}" in markdown
    assert r"\boldsymbol{x} & = \operatorname*{arg\,max}_y f(y)" in markdown
    assert r"\bm" not in markdown
    assert r"\argmax" not in markdown
    assert r"\label" not in markdown


@pytest.mark.asyncio
async def test_translated_markdown_preserves_figure_images_with_translated_caption(
    bilin_home: Path,
    tmp_path: Path,
) -> None:
    library = await create_library(
        LibraryCreate(name="Figure Export", path=str(tmp_path / "library")),
    )
    bundle_path = bundle_path_for_arxiv(library, "2401.00007", "v1")
    assets_dir = bundle_path / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    primary_path = assets_dir / "source-left.png"
    secondary_path = assets_dir / "source-right.png"
    primary_path.write_bytes(b"left")
    secondary_path.write_bytes(b"right")
    _, revision = await upsert_arxiv_revision(
        library,
        bare_id="2401.00007",
        version="v1",
        title="Figure Export",
        bundle_path=bundle_path,
        metadata={},
    )
    block = make_block(
        revision.id,
        block_uid="fig-0001",
        structural_path="00001",
        block_type="figure",
        source_markdown="**Figure 1.** Original caption.",
        metadata={"asset_id": "fig-0001"},
    )
    asset = make_asset(
        revision.id,
        asset_id="fig-0001",
        kind="figure",
        caption="Original caption.",
        web_path=str(primary_path),
        metadata={
            "asset_files": [
                {"index": 1, "web_path": str(primary_path)},
                {"index": 2, "web_path": str(secondary_path)},
            ],
        },
    )
    await replace_document(
        library,
        revision,
        ArticleManifest(article_revision_id=revision.id, source="arxiv"),
        [block],
        [asset],
        block.source_markdown,
    )
    await create_translation_variant(
        library=library,
        block=block,
        target_language="zh-CN",
        raw_markdown="**图 1.** 翻译图注。",
        provider_profile_id="provider",
        model="model",
        glossary_version="glossary:none",
    )

    result = await export_article(
        library,
        revision.id,
        ArticleExportRequest(
            kind=ArticleExportKind.translated_markdown,
            target_language="zh-CN",
            include_untranslated=False,
        ),
    )
    markdown, names = read_markdown_export(result.path)

    assert "![fig-0001](figure-export-translation-zh-CN.assets/fig-0001.png)" in markdown
    assert "![fig-0001](figure-export-translation-zh-CN.assets/fig-0001-2.png)" in markdown
    assert "**图 1.** 翻译图注。" in markdown
    assert "Original caption" not in markdown
    assert "figure-export-translation-zh-CN.assets/fig-0001.png" in names
    assert "figure-export-translation-zh-CN.assets/fig-0001-2.png" in names


@pytest.mark.asyncio
async def test_translated_markdown_preserves_tables_as_markdown_tables(
    bilin_home: Path,
    tmp_path: Path,
) -> None:
    library = await create_library(
        LibraryCreate(name="Table Export", path=str(tmp_path / "library")),
    )
    bundle_path = bundle_path_for_arxiv(library, "2401.00008", "v1")
    _, revision = await upsert_arxiv_revision(
        library,
        bare_id="2401.00008",
        version="v1",
        title="Table Export",
        bundle_path=bundle_path,
        metadata={},
    )
    translated_table = make_block(
        revision.id,
        block_uid="table-translated",
        structural_path="00001",
        block_type="table",
        source_markdown="**Table 1.** Original caption.",
        metadata={
            "html_fragment": """
            <table>
              <tr><th>Method</th><th>Score</th></tr>
              <tr><td>Alpha</td><td>0.91</td></tr>
            </table>
            """,
        },
    )
    untranslated_table = make_block(
        revision.id,
        block_uid="table-untranslated",
        structural_path="00002",
        block_type="table",
        source_markdown="**Table 2.** Caption without translation.",
        metadata={
            "html_fragment": """
            <table>
              <tr><th>Dataset</th><th>Size</th></tr>
              <tr><td>Eval</td><td>128</td></tr>
            </table>
            """,
        },
    )
    await replace_document(
        library,
        revision,
        ArticleManifest(article_revision_id=revision.id, source="arxiv"),
        [translated_table, untranslated_table],
        [],
        "\n\n".join((translated_table.source_markdown, untranslated_table.source_markdown)),
    )
    await create_translation_variant(
        library=library,
        block=translated_table,
        target_language="zh-CN",
        raw_markdown="**表 1.** 翻译表注。",
        provider_profile_id="provider",
        model="model",
        glossary_version="glossary:none",
    )

    result = await export_article(
        library,
        revision.id,
        ArticleExportRequest(
            kind=ArticleExportKind.translated_markdown,
            target_language="zh-CN",
            include_untranslated=False,
        ),
    )
    markdown, _ = read_markdown_export(result.path)

    assert "| Method | Score |" in markdown
    assert "| Alpha | 0.91 |" in markdown
    assert "**表 1.** 翻译表注。" in markdown
    assert "| Dataset | Size |" in markdown
    assert "| Eval | 128 |" in markdown
    assert "**Table 1.** Original caption." not in markdown
    assert "**Table 2.** Caption without translation." not in markdown
    assert "<table" not in markdown
    assert result.missing_translation_block_uids == ["table-untranslated"]


def test_html_table_export_is_markdown_table() -> None:
    markdown = html_table_to_markdown(
        """
        <table>
          <tr><th>Method</th><th>Error (%)</th></tr>
          <tr><td>ResNet-110</td><td>6.43 (6.61±0.16)</td></tr>
        </table>
        """
    )

    assert "<table" not in markdown
    assert "| Method | Error (%) |" in markdown
    assert "| ResNet-110 | 6.43 (6.61±0.16) |" in markdown


@pytest.mark.asyncio
async def test_export_job_runs_through_worker(
    bilin_home: Path,
    tmp_path: Path,
) -> None:
    library, revision_id, _ = await prepare_export_fixture(tmp_path)
    job = await queue_article_export(
        library,
        revision_id,
        ArticleExportRequest(kind=ArticleExportKind.source_markdown),
    )

    assert job.type == JobType.export_article
    await run_worker(once=True)
    completed = await get_job(job.id)

    assert completed is not None
    assert completed.status == JobStatus.succeeded
    assert completed.result is not None
    assert completed.result["file_name"] == "export-fixture-source.zip"
    assert completed.result["metadata"]["relative_path"] == "export/export-fixture-source.zip"


async def prepare_export_fixture(tmp_path: Path) -> tuple[Library, str, list[DocumentBlock]]:
    library = await create_library(
        LibraryCreate(name="Export", path=str(tmp_path / "library")),
    )
    bundle_path = bundle_path_for_arxiv(library, "2401.00005", "v1")
    _, revision = await upsert_arxiv_revision(
        library,
        bare_id="2401.00005",
        version="v1",
        title="Export fixture",
        bundle_path=bundle_path,
        metadata={},
    )
    asset_path = bundle_path / "assets" / "fig-0001.png"
    asset_path.parent.mkdir(parents=True, exist_ok=True)
    asset_path.write_bytes(b"fake png")
    blocks = [
        make_block(
            revision.id,
            block_uid="sec-0001",
            structural_path="00001",
            block_type="section",
            source_markdown="Introduction",
            metadata={"level": 1},
        ),
        make_block(
            revision.id,
            block_uid="p-0001",
            structural_path="00002",
            block_type="paragraph",
            source_markdown="A paragraph to translate.",
        ),
        make_block(
            revision.id,
            block_uid="eq-0001",
            structural_path="00003",
            block_type="equation",
            source_markdown="E=mc^2",
        ),
        make_block(
            revision.id,
            block_uid="fig-0001",
            structural_path="00004",
            block_type="figure",
            source_markdown="**Figure 1.** A missing translated caption.",
            metadata={"asset_id": "fig-0001"},
        ),
    ]
    assets = [
        make_asset(
            revision.id,
            asset_id="fig-0001",
            kind="figure",
            caption="A missing translated caption.",
            web_path=str(asset_path),
        )
    ]
    await replace_document(
        library,
        revision,
        ArticleManifest(article_revision_id=revision.id, source="arxiv"),
        blocks,
        assets,
        "\n\n".join(block.source_markdown for block in blocks),
    )
    return library, revision.id, blocks


def read_markdown_export(path: str) -> tuple[str, set[str]]:
    with zipfile.ZipFile(path) as archive:
        names = set(archive.namelist())
        markdown_name = next(name for name in names if name.endswith(".md"))
        return archive.read(markdown_name).decode("utf-8"), names
