from __future__ import annotations

CONTENT_NOTICE_ID = "bilin-content-notice:v1"

CONTENT_NOTICE_TEXT = (
    "Generated by Bilin for local research and study use. Imported paper content, "
    "figures, tables, captions, translations, and notes may belong to their original "
    "authors, publishers, or other rights holders. Redistribute this file only when "
    "permitted by the original license, the rights holder, or an applicable legal "
    "exception. Bilin source code is licensed under Apache-2.0."
)

MARKDOWN_CONTENT_WATERMARK = (
    f"<!-- {CONTENT_NOTICE_ID}\n{CONTENT_NOTICE_TEXT}\n/{CONTENT_NOTICE_ID} -->"
)


def with_markdown_content_watermark(markdown: str) -> str:
    normalized = markdown.lstrip()
    if normalized.startswith(f"<!-- {CONTENT_NOTICE_ID}"):
        return markdown
    return f"{MARKDOWN_CONTENT_WATERMARK}\n\n{markdown.lstrip()}"
