from __future__ import annotations

import html
import re
import shutil
import zipfile
from datetime import UTC, datetime
from html.parser import HTMLParser
from pathlib import Path

from bilin_api.article_store import (
    get_article_item,
    get_article_revision,
    list_assets,
    list_blocks,
    list_translation_variants,
    read_manifest,
    write_lecture_notes,
    write_manifest,
)
from bilin_api.content_notice import CONTENT_NOTICE_TEXT
from bilin_api.glossary_service import active_article_glossary_terms, apply_glossary_to_markdown
from bilin_api.repositories import create_job
from bilin_api.schemas import (
    ArticleExportKind,
    ArticleExportRequest,
    ArticleExportResult,
    AssetRecord,
    DocumentBlock,
    Job,
    JobType,
    Library,
    TranslationVariant,
)
from bilin_api.translation_service import is_translatable_block

EXPORT_NOTICE_TEXT = (
    "Generated by Ilios for local study. Paper content may belong to the original rights "
    "holders; do not redistribute without permission."
)


async def export_article(
    library: Library,
    revision_id: str,
    request: ArticleExportRequest,
) -> ArticleExportResult:
    revision = await get_article_revision(library, revision_id)
    if revision is None:
        msg = f"Article revision not found: {revision_id}"
        raise ValueError(msg)

    bundle_path = Path(revision.bundle_path)
    export_dir = bundle_path / "export"
    export_dir.mkdir(parents=True, exist_ok=True)

    missing: list[str] = []
    if request.kind == ArticleExportKind.source_markdown:
        output_path = await write_markdown_export_package(
            library,
            revision_id,
            export_dir,
            request,
            await render_source_markdown(library, revision_id),
        )
    elif request.kind == ArticleExportKind.translated_markdown:
        output_path = await write_markdown_export_package(
            library,
            revision_id,
            export_dir,
            request,
            await render_translated_markdown(
                library,
                revision_id,
                request.target_language,
                request.include_untranslated,
                missing,
            ),
        )
    elif request.kind == ArticleExportKind.bilingual_markdown:
        output_path = await write_markdown_export_package(
            library,
            revision_id,
            export_dir,
            request,
            await render_bilingual_markdown(
                library,
                revision_id,
                request.target_language,
                request.include_untranslated,
                missing,
            ),
        )
    elif request.kind == ArticleExportKind.lecture_notes:
        notes_path = await write_lecture_notes(library, revision_id)
        output_path = await write_markdown_export_package(
            library,
            revision_id,
            export_dir,
            request,
            notes_path.read_text(encoding="utf-8"),
        )
    elif request.kind == ArticleExportKind.bundle_zip:
        output_path = export_dir / "article-bundle.zip"
        write_bundle_zip(bundle_path, output_path)
    else:
        msg = f"Unsupported export kind: {request.kind}"
        raise ValueError(msg)

    result = ArticleExportResult(
        article_revision_id=revision_id,
        kind=request.kind,
        target_language=target_language_for_result(request.kind, request.target_language),
        file_name=output_path.name,
        path=str(output_path),
        bytes_written=output_path.stat().st_size,
        missing_translation_block_uids=sorted(set(missing)),
        metadata=export_metadata(bundle_path, export_dir, output_path),
        created_at=datetime.now(UTC),
    )
    write_export_manifest_entry(bundle_path, result)
    return result


async def queue_article_export(
    library: Library,
    revision_id: str,
    request: ArticleExportRequest,
) -> Job:
    revision = await get_article_revision(library, revision_id)
    if revision is None:
        msg = f"Article revision not found: {revision_id}"
        raise ValueError(msg)
    return await create_job(
        JobType.export_article,
        payload={
            "library_id": library.id,
            "article_revision_id": revision_id,
            "request": request.model_dump(mode="json"),
        },
    )


async def render_source_markdown(library: Library, revision_id: str) -> str:
    blocks = await list_blocks(library, revision_id)
    assets = await export_assets_by_id(library, revision_id)
    return render_markdown_document(
        title=await export_article_title(library, revision_id, "Source Markdown"),
        body_parts=[render_source_block(block, assets) for block in blocks],
    )


async def render_translated_markdown(
    library: Library,
    revision_id: str,
    target_language: str,
    include_untranslated: bool,
    missing: list[str],
) -> str:
    blocks = await list_blocks(library, revision_id)
    assets = await export_assets_by_id(library, revision_id)
    translations = await default_translation_by_block_uid(library, revision_id, target_language)
    body_parts = [
        render_translated_block(block, assets, translations, include_untranslated, missing)
        for block in blocks
    ]
    return render_markdown_document(
        title=await export_article_title(library, revision_id, f"Translation ({target_language})"),
        body_parts=[part for part in body_parts if part],
    )


async def render_bilingual_markdown(
    library: Library,
    revision_id: str,
    target_language: str,
    include_untranslated: bool,
    missing: list[str],
) -> str:
    blocks = await list_blocks(library, revision_id)
    assets = await export_assets_by_id(library, revision_id)
    translations = await default_translation_by_block_uid(library, revision_id, target_language)
    parts: list[str] = []
    for block in blocks:
        translation = translation_for_block(
            block, assets, translations, include_untranslated, missing
        )
        source = render_source_content(block, assets)
        if not source and not translation:
            continue
        parts.append(
            "\n\n".join(
                part
                for part in (
                    f"### {readable_block_label(block)}",
                    f"**Source**\n\n{source}" if source else "",
                    f"**Translation ({target_language})**",
                    translation or "_Translation unavailable._",
                )
                if part
            )
        )
    return render_markdown_document(
        title=await export_article_title(library, revision_id, f"Bilingual ({target_language})"),
        body_parts=parts,
    )


def render_markdown_document(title: str, body_parts: list[str]) -> str:
    body = "\n\n".join(part.strip() for part in body_parts if part.strip())
    markdown = f"# {title}\n\n{body}".strip() + "\n"
    return with_export_notice(clean_user_markdown(markdown))


def render_source_block(block: DocumentBlock, assets: dict[str, AssetRecord]) -> str:
    return render_source_content(block, assets)


def render_source_content(block: DocumentBlock, assets: dict[str, AssetRecord]) -> str:
    content = user_content_for_block(block, assets)
    if block.block_type == "section" and content and not content.startswith("#"):
        level = block.metadata.get("level")
        heading_level = level if isinstance(level, int) and 1 <= level <= 6 else 2
        return f"{'#' * heading_level} {content}"
    return content


def render_translated_block(
    block: DocumentBlock,
    assets: dict[str, AssetRecord],
    translations: dict[str, str],
    include_untranslated: bool,
    missing: list[str],
) -> str:
    return translation_for_block(block, assets, translations, include_untranslated, missing)


def translation_for_block(
    block: DocumentBlock,
    assets: dict[str, AssetRecord],
    translations: dict[str, str],
    include_untranslated: bool,
    missing: list[str],
) -> str:
    if is_translatable_block(block):
        translated = translations.get(block.block_uid)
        if translated:
            return translated
        missing.append(block.block_uid)
        if not include_untranslated:
            return ""
        return render_source_content(block, assets)
    return render_source_content(block, assets)


async def default_translation_by_block_uid(
    library: Library,
    revision_id: str,
    target_language: str,
) -> dict[str, str]:
    active_terms = await active_article_glossary_terms(library, revision_id, target_language)
    translations: dict[str, str] = {}
    for variant in await list_translation_variants(library, revision_id, target_language):
        block_uid = block_uid_for_variant(variant)
        if not block_uid:
            continue
        if block_uid not in translations or variant.is_default:
            translations[block_uid] = apply_glossary_to_markdown(variant.raw_markdown, active_terms)
    return translations


def block_uid_for_variant(variant: TranslationVariant) -> str | None:
    block_uid = variant.metadata.get("block_uid")
    return block_uid if isinstance(block_uid, str) and block_uid else None


async def export_assets_by_id(library: Library, revision_id: str) -> dict[str, AssetRecord]:
    return {asset.asset_id: asset for asset in await list_assets(library, revision_id)}


async def export_article_title(library: Library, revision_id: str, fallback: str) -> str:
    item = await get_article_item(library, revision_id)
    title = item.family.title if item and item.family.title else None
    return title.strip() if title and title.strip() else fallback


async def write_markdown_export_package(
    library: Library,
    revision_id: str,
    export_dir: Path,
    request: ArticleExportRequest,
    markdown: str,
) -> Path:
    title = await export_article_title(library, revision_id, "paper")
    base_name = export_base_name(title, request)
    package_dir = export_dir / base_name
    if package_dir.exists():
        shutil.rmtree(package_dir)
    package_dir.mkdir(parents=True)
    assets_dir = package_dir / f"{base_name}.assets"
    asset_paths = await copy_markdown_export_assets(library, revision_id, assets_dir)
    markdown = with_export_notice(clean_user_markdown(markdown))
    markdown = rewrite_asset_tokens(markdown, asset_paths, f"{base_name}.assets")
    markdown_path = package_dir / f"{base_name}.md"
    markdown_path.write_text(markdown, encoding="utf-8")
    output_path = export_dir / f"{base_name}.zip"
    if output_path.exists():
        output_path.unlink()
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.write(markdown_path, markdown_path.name)
        if assets_dir.exists():
            for path in sorted(assets_dir.rglob("*")):
                if path.is_file():
                    archive.write(path, Path(assets_dir.name) / path.relative_to(assets_dir))
    return output_path


async def copy_markdown_export_assets(
    library: Library,
    revision_id: str,
    assets_dir: Path,
) -> dict[str, list[str]]:
    copied: dict[str, list[str]] = {}
    for asset in await list_assets(library, revision_id):
        for source_path in asset_export_source_paths(asset):
            if not source_path.exists() or not source_path.is_file():
                continue
            assets_dir.mkdir(parents=True, exist_ok=True)
            target_name = unique_asset_file_name(
                assets_dir,
                safe_file_token(f"{asset.asset_id}{source_path.suffix}") or source_path.name,
            )
            target = assets_dir / target_name
            shutil.copy2(source_path, target)
            copied.setdefault(asset.asset_id, []).append(target.name)
    return copied


def asset_export_source_paths(asset: AssetRecord) -> list[Path]:
    paths: list[Path] = []
    if asset.web_path:
        paths.append(Path(asset.web_path))
    asset_files = asset.metadata.get("asset_files")
    if isinstance(asset_files, list):
        for item in asset_files:
            if not isinstance(item, dict):
                continue
            web_path = item.get("web_path")
            if isinstance(web_path, str) and web_path:
                paths.append(Path(web_path))
    unique: list[Path] = []
    seen: set[Path] = set()
    for path in paths:
        resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        unique.append(resolved)
    return unique


def unique_asset_file_name(directory: Path, file_name: str) -> str:
    candidate = file_name
    stem = Path(file_name).stem or "asset"
    suffix = Path(file_name).suffix
    index = 2
    while (directory / candidate).exists():
        candidate = f"{stem}-{index}{suffix}"
        index += 1
    return candidate


def rewrite_asset_tokens(
    markdown: str,
    asset_paths: dict[str, list[str]],
    assets_dir_name: str,
) -> str:
    for asset_id, file_names in asset_paths.items():
        if not file_names:
            continue
        links = "\n".join(
            f"![{asset_id}]({assets_dir_name}/{file_name})" for file_name in file_names
        )
        markdown = markdown.replace(asset_token(asset_id), links)
    return re.sub(r"\n?<!-- ilios-asset:[^>]+ -->\n?", "\n", markdown)


def user_content_for_block(block: DocumentBlock, assets: dict[str, AssetRecord]) -> str:
    content = block.source_markdown.strip()
    if block.block_type in {"figure", "table"}:
        asset_id = str(block.metadata.get("asset_id") or "")
        asset = assets.get(asset_id)
        table = markdown_table_for_block(block, asset)
        asset_link = asset_token(asset_id) if asset and asset_id else ""
        content = "\n\n".join(part for part in (asset_link, table or content) if part)
    return clean_user_markdown(content)


def markdown_table_for_block(block: DocumentBlock, asset: AssetRecord | None) -> str:
    html_fragment = html_fragment_for_block(block, asset)
    if html_fragment and "<table" in html_fragment.lower():
        table = html_table_to_markdown(html_fragment)
        if table:
            caption = clean_user_markdown(block.source_markdown.strip())
            return "\n\n".join(part for part in (table, caption) if part)
    return ""


def html_fragment_for_block(block: DocumentBlock, asset: AssetRecord | None) -> str:
    for source in (block.metadata, asset.metadata if asset else {}):
        value = source.get("html_fragment")
        if isinstance(value, str) and value.strip():
            return value
    return ""


def asset_token(asset_id: str) -> str:
    return f"<!-- ilios-asset:{asset_id} -->"


def clean_user_markdown(markdown: str) -> str:
    cleaned = strip_internal_markers(markdown)
    cleaned = convert_html_tables_in_markdown(cleaned)
    cleaned = strip_unwanted_html(cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()


def strip_internal_markers(markdown: str) -> str:
    cleaned = re.sub(
        r"<!--\s*bilin-content-notice:v1.*?/bilin-content-notice:v1\s*-->",
        "",
        markdown,
        flags=re.DOTALL,
    )
    cleaned = re.sub(r"<!--\s*/?bilin-note-patch:[^>]*-->", "", cleaned)
    cleaned = re.sub(r"<!--\s*untranslated:[^>]*-->", "", cleaned)
    cleaned = re.sub(r"<a\s+id=[\"'][^\"']+[\"']\s*></a>", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^Article revision:\s*`[^`]+`\s*$", "", cleaned, flags=re.MULTILINE)
    cleaned = re.sub(r"^Source refs:\s*.*$", "", cleaned, flags=re.MULTILINE)
    return cleaned


def convert_html_tables_in_markdown(markdown: str) -> str:
    return re.sub(
        r"<table\b.*?</table>",
        lambda match: html_table_to_markdown(match.group(0)) or "",
        markdown,
        flags=re.IGNORECASE | re.DOTALL,
    )


def strip_unwanted_html(markdown: str) -> str:
    cleaned = re.sub(r"<br\s*/?>", "\n", markdown, flags=re.IGNORECASE)
    cleaned = re.sub(r"</p\s*>", "\n\n", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"<p\b[^>]*>", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(
        r"</?(?:span|div|section|article|tbody|thead|tr|td|th)[^>]*>",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    return html.unescape(cleaned)


def html_table_to_markdown(fragment: str) -> str:
    parser = _TableMarkdownParser()
    parser.feed(fragment)
    rows = parser.rows
    if not rows:
        return ""
    width = max(len(row) for row in rows)
    normalized = [row + [""] * (width - len(row)) for row in rows]
    header = normalized[0]
    body = normalized[1:]
    separator = ["---"] * width
    lines = [
        markdown_table_row(header),
        markdown_table_row(separator),
        *(markdown_table_row(row) for row in body),
    ]
    return "\n".join(lines)


class _TableMarkdownParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.rows: list[list[str]] = []
        self._current_row: list[str] | None = None
        self._current_cell: list[str] | None = None
        self._cell_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        del attrs
        if tag.lower() == "tr":
            self._current_row = []
        elif tag.lower() in {"td", "th"} and self._current_row is not None:
            self._current_cell = []
            self._cell_depth = 1
        elif self._current_cell is not None and tag.lower() == "br":
            self._current_cell.append(" ")

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if tag in {"td", "th"} and self._current_row is not None and self._current_cell is not None:
            self._current_row.append(" ".join("".join(self._current_cell).split()))
            self._current_cell = None
            self._cell_depth = 0
        elif tag == "tr" and self._current_row is not None:
            if any(cell.strip() for cell in self._current_row):
                self.rows.append(self._current_row)
            self._current_row = None

    def handle_data(self, data: str) -> None:
        if self._current_cell is not None:
            self._current_cell.append(data)


def markdown_table_row(cells: list[str]) -> str:
    escaped = [cell.replace("|", "\\|").strip() or " " for cell in cells]
    return f"| {' | '.join(escaped)} |"


def export_base_name(title: str, request: ArticleExportRequest) -> str:
    parts = [safe_slug_token(title) or "paper", export_mode_token(request.kind)]
    if request.kind in {
        ArticleExportKind.translated_markdown,
        ArticleExportKind.bilingual_markdown,
    }:
        parts.append(safe_file_token(request.target_language))
    return "-".join(part for part in parts if part)


def export_mode_token(kind: ArticleExportKind) -> str:
    if kind == ArticleExportKind.source_markdown:
        return "source"
    if kind == ArticleExportKind.translated_markdown:
        return "translation"
    if kind == ArticleExportKind.bilingual_markdown:
        return "bilingual"
    if kind == ArticleExportKind.lecture_notes:
        return "lecture-notes"
    return "bundle"


def readable_block_label(block: DocumentBlock) -> str:
    if block.block_type == "paragraph":
        return "Paragraph"
    return block.block_type.replace("_", " ").title()


def with_export_notice(markdown: str) -> str:
    notice = f"> {EXPORT_NOTICE_TEXT}"
    if notice in markdown:
        return markdown if markdown.endswith("\n") else f"{markdown}\n"
    return f"{markdown.rstrip()}\n\n---\n\n{notice}\n"


def write_bundle_zip(bundle_path: Path, output_path: Path) -> None:
    if output_path.exists():
        output_path.unlink()
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("BILIN_CONTENT_NOTICE.txt", CONTENT_NOTICE_TEXT + "\n")
        for path in sorted(bundle_path.rglob("*")):
            if not path.is_file() or path == output_path:
                continue
            archive.write(path, path.relative_to(bundle_path))


def write_export_manifest_entry(bundle_path: Path, result: ArticleExportResult) -> None:
    manifest = read_manifest(bundle_path)
    if manifest is None:
        return
    exports = manifest.generated_artifacts.get("exports")
    if not isinstance(exports, dict):
        exports = {}
    exports[result.kind.value] = {
        "path": result.path,
        "file_name": result.file_name,
        "target_language": result.target_language,
        "bytes_written": result.bytes_written,
        "created_at": result.created_at.isoformat(),
        "missing_translation_block_uids": result.missing_translation_block_uids,
        "metadata": result.metadata,
    }
    manifest.generated_artifacts["exports"] = exports
    write_manifest(bundle_path, manifest)


def export_metadata(bundle_path: Path, export_dir: Path, output_path: Path) -> dict[str, str]:
    return {
        "bundle_path": str(bundle_path),
        "export_dir": str(export_dir),
        "manifest_path": str(bundle_path / "manifest.json"),
        "relative_path": output_path.relative_to(bundle_path).as_posix(),
        "content_notice": "bilin-content-notice:v1",
    }


def target_language_for_result(kind: ArticleExportKind, target_language: str) -> str | None:
    if kind in {ArticleExportKind.translated_markdown, ArticleExportKind.bilingual_markdown}:
        return target_language
    return None


def safe_file_token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9_.-]+", "-", value.strip())
    return token.strip(".-") or "target"


def safe_slug_token(value: str) -> str:
    return safe_file_token(value).lower()
